import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import type { BabConfig } from "../src/config";
import {
  generateSkillContent,
  STATIC_TOOL_NAMES,
} from "../src/skills/generator";
import {
  computeFingerprint,
  discoverAgents,
  isStale,
  regenerateSkills,
  type SkillContent,
} from "../src/skills/index";
import { VERSION } from "../src/version";

function makeTempConfig(baseDir: string): BabConfig {
  return {
    env: {},
    paths: {
      baseDir,
      envFile: join(baseDir, "env"),
      pluginsDir: join(baseDir, "plugins"),
      promptsDir: join(baseDir, "prompts"),
    },
  };
}

function makeStubContent(): SkillContent {
  return {
    skillMd: `---
name: bab
description: Test skill
user-invocable: false
---
<!-- Auto-generated by bab v${VERSION} -->
# Bab MCP Tools
`,
    toolsReference: "# Tools Reference\n",
    delegatePluginsReference: "# Delegate Plugins Reference\n",
  };
}

function captureStderr(): {
  stream: { write(chunk: string): boolean };
  output: string[];
} {
  const output: string[] = [];
  return {
    stream: {
      write(chunk: string) {
        output.push(chunk);
        return true;
      },
    },
    output,
  };
}

describe("computeFingerprint", () => {
  test("produces a 64-char hex string", () => {
    const fp = computeFingerprint("1.0.0", ["a"], ["chat"]);
    expect(fp).toMatch(/^[0-9a-f]{64}$/);
  });

  test("same inputs produce same fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["x", "y"], ["chat", "debug"]);
    const b = computeFingerprint("1.0.0", ["x", "y"], ["chat", "debug"]);
    expect(a).toBe(b);
  });

  test("order of plugins and tools does not matter", () => {
    const a = computeFingerprint("1.0.0", ["b", "a"], ["debug", "chat"]);
    const b = computeFingerprint("1.0.0", ["a", "b"], ["chat", "debug"]);
    expect(a).toBe(b);
  });

  test("different version produces different fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["a"], ["chat"]);
    const b = computeFingerprint("2.0.0", ["a"], ["chat"]);
    expect(a).not.toBe(b);
  });

  test("different plugins produce different fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["a"], ["chat"]);
    const b = computeFingerprint("1.0.0", ["a", "b"], ["chat"]);
    expect(a).not.toBe(b);
  });
});

describe("isStale", () => {
  test("returns true when no existing metadata", () => {
    expect(isStale(undefined, "abc123")).toBeTrue();
  });

  test("returns true when fingerprints differ", () => {
    const existing = {
      schema_version: 1 as const,
      bab_version: VERSION,
      generated_at: new Date().toISOString(),
      fingerprint: "old-fingerprint",
    };
    expect(isStale(existing, "new-fingerprint")).toBeTrue();
  });

  test("returns false when fingerprints match", () => {
    const fp = "matching-fingerprint";
    const existing = {
      schema_version: 1 as const,
      bab_version: VERSION,
      generated_at: new Date().toISOString(),
      fingerprint: fp,
    };
    expect(isStale(existing, fp)).toBeFalse();
  });
});

describe("discoverAgents", () => {
  test("returns agents whose config directories exist", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const agents = await discoverAgents(undefined, home);

    expect(agents.length).toBe(1);
    expect(agents[0].id).toBe("claude");
  });

  test("returns empty when no agent directories exist", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-empty-"));
    const agents = await discoverAgents(undefined, home);
    expect(agents).toEqual([]);
  });

  test("filters by agent id", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-filter-"));
    await mkdir(join(home, ".claude"), { recursive: true });
    await mkdir(join(home, ".codex"), { recursive: true });

    const claude = await discoverAgents("claude", home);
    expect(claude.length).toBe(1);
    expect(claude[0].id).toBe("claude");

    const codex = await discoverAgents("codex", home);
    expect(codex.length).toBe(1);
    expect(codex[0].id).toBe("codex");

    const unknown = await discoverAgents("unknown-agent", home);
    expect(unknown).toEqual([]);
  });
});

describe("regenerateSkills", () => {
  test("writes skill directory for discovered agents", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-regen-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();
    const content = makeStubContent();

    const result = await regenerateSkills(config, async () => content, {
      force: true,
      agent: "claude",
      home,
      stderr: stderr.stream,
      toolNames: ["chat"],
      pluginIds: [],
    });

    expect(result.agentsUpdated).toContain("claude");

    const skillMdPath = join(home, ".claude", "skills", "bab", "SKILL.md");
    const metadataPath = join(
      home,
      ".claude",
      "skills",
      "bab",
      ".bab-skills.json",
    );
    const toolsRefPath = join(
      home,
      ".claude",
      "skills",
      "bab",
      "references",
      "tools.md",
    );

    expect((await stat(skillMdPath)).isFile()).toBeTrue();
    expect((await stat(metadataPath)).isFile()).toBeTrue();
    expect((await stat(toolsRefPath)).isFile()).toBeTrue();

    const metadata = JSON.parse(await Bun.file(metadataPath).text());
    expect(metadata.schema_version).toBe(1);
    expect(metadata.bab_version).toBe(VERSION);
    expect(metadata.fingerprint).toMatch(/^[0-9a-f]{64}$/);
  });

  test("skips agents when fingerprint is fresh (not forced)", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-skip-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();
    const content = makeStubContent();

    const firstResult = await regenerateSkills(config, async () => content, {
      force: true,
      home,
      stderr: stderr.stream,
      toolNames: ["chat"],
      pluginIds: [],
    });

    expect(firstResult.agentsUpdated).toContain("claude");

    const secondResult = await regenerateSkills(config, async () => content, {
      force: false,
      home,
      stderr: stderr.stream,
      toolNames: ["chat"],
      pluginIds: [],
    });

    expect(secondResult.skipped).toContain("claude");
    expect(secondResult.agentsUpdated).not.toContain("claude");
  });

  test("returns empty when no agents detected", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-noagent-"));
    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();

    const result = await regenerateSkills(
      config,
      async () => makeStubContent(),
      {
        agent: "nonexistent-agent",
        home,
        stderr: stderr.stream,
        toolNames: [],
        pluginIds: [],
      },
    );

    expect(result.agentsUpdated).toEqual([]);
    expect(result.skipped).toEqual([]);
  });

  test("skips user-modified SKILL.md", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-usermod-"));
    const skillBabDir = join(home, ".claude", "skills", "bab");
    await mkdir(skillBabDir, { recursive: true });

    await Bun.write(
      join(skillBabDir, "SKILL.md"),
      "---\nname: bab\n---\n# My custom skill notes\n",
    );

    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();

    const result = await regenerateSkills(
      config,
      async () => makeStubContent(),
      {
        force: true,
        home,
        stderr: stderr.stream,
        toolNames: ["chat"],
        pluginIds: [],
      },
    );

    expect(result.skipped).toContain("claude");
    expect(stderr.output.join("")).toContain("user-modified");
  });

  test("skips when lock is held", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-lock-"));
    const skillsDir = join(home, ".claude", "skills");
    await mkdir(join(skillsDir, ".bab-skillgen.lock"), { recursive: true });

    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();

    const result = await regenerateSkills(
      config,
      async () => makeStubContent(),
      {
        force: true,
        home,
        stderr: stderr.stream,
        toolNames: ["chat"],
        pluginIds: [],
      },
    );

    expect(result.skipped).toContain("claude");
    expect(stderr.output.join("")).toContain("already in progress");
  });

  test("cleans up orphan staging directories", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-orphan-"));
    const skillsDir = join(home, ".claude", "skills");
    const orphanStaging = join(skillsDir, ".bab-staging-old-nonce");
    const orphanOld = join(skillsDir, ".bab-old-old-nonce");
    await mkdir(orphanStaging, { recursive: true });
    await mkdir(orphanOld, { recursive: true });

    const config = makeTempConfig(join(home, "config"));
    const stderr = captureStderr();

    await regenerateSkills(config, async () => makeStubContent(), {
      force: true,
      home,
      stderr: stderr.stream,
      toolNames: ["chat"],
      pluginIds: [],
    });

    let stagingExists = true;
    let oldExists = true;
    try {
      await stat(orphanStaging);
    } catch {
      stagingExists = false;
    }
    try {
      await stat(orphanOld);
    } catch {
      oldExists = false;
    }

    expect(stagingExists).toBeFalse();
    expect(oldExists).toBeFalse();
  });
});

describe("STATIC_TOOL_NAMES", () => {
  test("contains expected core tools", () => {
    expect(STATIC_TOOL_NAMES).toContain("chat");
    expect(STATIC_TOOL_NAMES).toContain("thinkdeep");
    expect(STATIC_TOOL_NAMES).toContain("codereview");
    expect(STATIC_TOOL_NAMES).toContain("delegate");
    expect(STATIC_TOOL_NAMES).toContain("version");
  });

  test("has no duplicates", () => {
    const unique = new Set(STATIC_TOOL_NAMES);
    expect(unique.size).toBe(STATIC_TOOL_NAMES.length);
  });
});

describe("generateSkillContent", () => {
  test("generates SKILL.md with frontmatter and auto-generated marker", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const content = await generateSkillContent(config);

    expect(content.skillMd).toContain("---\nname: bab");
    expect(content.skillMd).toContain("user-invocable: false");
    expect(content.skillMd).toContain(`Auto-generated by bab v${VERSION}`);
    expect(content.skillMd).toContain("| Tool | Description | When to use |");
  });

  test("generates tools reference with all catalog entries", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-tools-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const content = await generateSkillContent(config);

    for (const toolName of STATIC_TOOL_NAMES) {
      expect(content.toolsReference).toContain(`## \`${toolName}\``);
    }
  });

  test("generates delegate plugins reference", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-plugins-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const content = await generateSkillContent(config);

    expect(content.delegatePluginsReference).toContain(
      "Delegate Plugins Reference",
    );
  });
});
