import { createHash } from "node:crypto";
import { mkdir, rename, rm, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

import { z } from "zod/v4";
import type { WritableLike } from "../commands/shared";
import type { BabConfig } from "../config";
import { VERSION } from "../version";

export interface AgentTarget {
  id: string;
  configDir: string;
  skillsDir: string;
}

export interface RegenerateSkillsOptions {
  force?: boolean;
  agent?: string;
  stderr?: WritableLike;
  toolNames?: string[];
  pluginIds?: string[];
}

export interface SkillContent {
  skillMd: string;
  toolsReference: string;
  delegatePluginsReference: string;
}

const SkillsMetadataSchema = z.object({
  schema_version: z.literal(1),
  bab_version: z.string(),
  generated_at: z.string(),
  fingerprint: z.string(),
});

type SkillsMetadata = z.infer<typeof SkillsMetadataSchema>;

const AUTO_GENERATED_MARKER = "<!-- Auto-generated by bab v";

function getKnownAgents(home = homedir()): AgentTarget[] {
  return [
    {
      id: "claude",
      configDir: join(home, ".claude"),
      skillsDir: join(home, ".claude", "skills"),
    },
    {
      id: "codex",
      configDir: join(home, ".codex"),
      skillsDir: join(home, ".codex", "skills"),
    },
  ];
}

async function directoryExists(path: string): Promise<boolean> {
  try {
    const stats = await stat(path);
    return stats.isDirectory();
  } catch {
    return false;
  }
}

export async function discoverAgents(
  agentFilter?: string,
  home?: string,
): Promise<AgentTarget[]> {
  const known = getKnownAgents(home);
  const candidates = agentFilter
    ? known.filter((a) => a.id === agentFilter)
    : known;

  const detected: AgentTarget[] = [];

  for (const agent of candidates) {
    if (await directoryExists(agent.configDir)) {
      detected.push(agent);
    }
  }

  return detected;
}

export function computeFingerprint(
  babVersion: string,
  pluginIds: string[],
  toolNames: string[],
): string {
  const sorted_plugins = [...pluginIds].sort();
  const sorted_tools = [...toolNames].sort();
  const input = `${babVersion}:${sorted_plugins.join(",")}:${sorted_tools.join(",")}`;
  return createHash("sha256").update(input).digest("hex");
}

async function readMetadata(
  skillDir: string,
): Promise<SkillsMetadata | undefined> {
  const metadataPath = join(skillDir, "bab", ".bab-skills.json");

  try {
    const contents = await Bun.file(metadataPath).text();
    return SkillsMetadataSchema.parse(JSON.parse(contents));
  } catch {
    return undefined;
  }
}

export function isStale(
  existing: SkillsMetadata | undefined,
  currentFingerprint: string,
): boolean {
  if (!existing) {
    return true;
  }

  return existing.fingerprint !== currentFingerprint;
}

async function isUserModified(
  skillDir: string,
  stderr: WritableLike,
): Promise<boolean> {
  const skillMdPath = join(skillDir, "bab", "SKILL.md");

  try {
    const contents = await Bun.file(skillMdPath).text();

    if (!contents.includes(AUTO_GENERATED_MARKER)) {
      stderr.write(
        `Warning: ${skillMdPath} appears user-modified (missing auto-generated header), skipping\n`,
      );
      return true;
    }

    return false;
  } catch {
    return false;
  }
}

async function writeSkillDirectory(
  skillsDir: string,
  content: SkillContent,
  metadata: SkillsMetadata,
  stderr: WritableLike,
): Promise<boolean> {
  const nonce = crypto.randomUUID();
  const stagingDir = join(skillsDir, `.bab-staging-${nonce}`);
  const finalDir = join(skillsDir, "bab");
  const oldDir = join(skillsDir, `.bab-old-${nonce}`);
  let movedOld = false;

  try {
    await mkdir(stagingDir, { recursive: true });
    await mkdir(join(stagingDir, "references"), { recursive: true });

    await Bun.write(join(stagingDir, "SKILL.md"), content.skillMd);
    await Bun.write(
      join(stagingDir, "references", "tools.md"),
      content.toolsReference,
    );
    await Bun.write(
      join(stagingDir, "references", "delegate-plugins.md"),
      content.delegatePluginsReference,
    );
    await Bun.write(
      join(stagingDir, ".bab-skills.json"),
      `${JSON.stringify(metadata, null, 2)}\n`,
    );

    if (await directoryExists(finalDir)) {
      await rename(finalDir, oldDir);
      movedOld = true;
    }

    await rename(stagingDir, finalDir);

    if (movedOld) {
      await rm(oldDir, { force: true, recursive: true });
    }

    return true;
  } catch (error) {
    if (movedOld && (await directoryExists(oldDir))) {
      try {
        if (await directoryExists(finalDir)) {
          await rm(finalDir, { force: true, recursive: true });
        }
        await rename(oldDir, finalDir);
      } catch {
        stderr.write(
          `Warning: failed to restore previous bab skill directory at ${finalDir}\n`,
        );
      }
    }

    await rm(stagingDir, { force: true, recursive: true }).catch(() => {});

    throw error;
  }
}

export async function regenerateSkills(
  _config: BabConfig,
  generateContent: (
    pluginIds: string[],
    toolNames: string[],
  ) => Promise<SkillContent>,
  options: RegenerateSkillsOptions = {},
): Promise<{ agentsUpdated: string[]; skipped: string[] }> {
  const stderr = options.stderr ?? process.stderr;
  const toolNames = options.toolNames ?? [];
  const pluginIds = options.pluginIds ?? [];
  const fingerprint = computeFingerprint(VERSION, pluginIds, toolNames);

  const agents = await discoverAgents(options.agent);

  if (agents.length === 0) {
    return { agentsUpdated: [], skipped: [] };
  }

  const agentsUpdated: string[] = [];
  const skipped: string[] = [];

  let content: SkillContent | undefined;

  for (const agent of agents) {
    try {
      if (!(await directoryExists(agent.skillsDir))) {
        await mkdir(agent.skillsDir, { recursive: true });
      }

      if (!options.force) {
        const existing = await readMetadata(agent.skillsDir);

        if (!isStale(existing, fingerprint)) {
          skipped.push(agent.id);
          continue;
        }
      }

      if (await isUserModified(agent.skillsDir, stderr)) {
        skipped.push(agent.id);
        continue;
      }

      if (!content) {
        content = await generateContent(pluginIds, toolNames);
      }

      const metadata: SkillsMetadata = {
        schema_version: 1,
        bab_version: VERSION,
        generated_at: new Date().toISOString(),
        fingerprint,
      };

      const written = await writeSkillDirectory(
        agent.skillsDir,
        content,
        metadata,
        stderr,
      );

      if (written) {
        agentsUpdated.push(agent.id);
      }
    } catch (error) {
      stderr.write(
        `Warning: failed to write skills for ${agent.id}: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      skipped.push(agent.id);
    }
  }

  return { agentsUpdated, skipped };
}
